### ISSUE TITLE
API Error Exception

### ISSUE THREAD

**Issue by AR-Coding-126** [tinycoder2/FaceFind#1]
Microsoft Azure Face API gives APIErrorException: (InvalidRequest) Invalid request has been sent
any help will be much appreciated

After many many attempts and hours of research, I have tried many other examples online and thought. Yet, still same error.

Seems the API doesn't like the .create request. any help will be much appreciated
![image](https://user-images.githubusercontent.com/100079496/234280272-5b4a2759-3c60-4901-866d-c0e09d25b2b7.png)

**Comment by Sarthakdtu** [comment]
It's probably due to the failure of the below line in **views.py**
`face_client = FaceClient(config['ENDPOINT'], CognitiveServicesCredentials(config['KEY']))`

Check your azure endpoint
